# Generated by Django 4.2.7 on 2023-12-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_yourimagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('image_src', models.TextField()),
            ],
        ),
    ]
