# Generated by Django 4.2.7 on 2023-12-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_photo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo1',
            name='image_src',
            field=models.TextField(null=True),
        ),
    ]
